# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "meanings", :force => true do |t|
    t.column "word_id",         :integer
    t.column "synonym_word_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "name",     :string
    t.column "login",    :string, :limit => 30, :null => false
    t.column "password", :string, :limit => 30, :null => false
    t.column "email",    :string, :limit => 30, :null => false
  end

  create_table "words", :force => true do |t|
    t.column "name", :string,              :null => false
    t.column "lang", :string, :limit => 2, :null => false
  end

end
