# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "languages", :force => true do |t|
    t.column "name", :string, :null => false
    t.column "code", :string, :null => false
  end

  create_table "meanings", :force => true do |t|
    t.column "word_id",         :integer
    t.column "synonym_word_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "login",           :string, :limit => 30, :null => false
    t.column "email",           :string, :limit => 30, :null => false
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

  create_table "words", :force => true do |t|
    t.column "name", :string,              :null => false
    t.column "lang", :string, :limit => 2, :null => false
  end

end
